services:
  mader_database:
    image: postgres
    env_file:
      - ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mader_app:
    image: mader_app 
    entrypoint: ./entrypoint.sh
    build: ./backend/
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - mader_database

  vue_app:
    image: vue_app
    build: ./frontend
    ports:
      - "8080:8080"
volumes:
  pgdata:

